export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';

export const GET_CHAT_LISTS_REQUEST = 'GET_CHATS_LISTS_REQUEST';
export const GET_CHAT_LISTS_SUCCESS = 'GET_CHATS_LISTS_SUCCESS';
export const GET_CHAT_LISTS_FAIL = 'GET_CHATS_LISTS_FAIL';
