export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';
export const CHANGE_CHAT_PARTNERS = 'CHANGE_CHAT_PARTNERS';
export const RESET_CHAT_PARTNERS = 'RESET_CHAT_PARTNERS';

export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';
