export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';
export const CHANGE_CHAT_PARTNERS = 'CHANGE_CHAT_PARTNERS';
export const RESET_CHAT_PARTNERS = 'RESET_CHAT_PARTNERS';
export const ADD_USER_GROUP_REQUEST = 'ADD_USER_GROUP_REQUEST';
export const ADD_USER_GROUP_SUCCESS = 'ADD_USER_GROUP_SUCCESS';
export const ADD_USER_GROUP_FAIL = 'ADD_USER_GROUP_FAIL';
export const ADD_USER_GROUP_RESET = 'ADD_USER_GROUP_RESET';

export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';
export const ADD_CHAT = 'ADD_CHAT';
export const RESET_CHAT_REDIRECT = 'RESET_CHAT_REDIRECT';
export const UPDATE_LAST_MESSAGE = 'UPDATE_LAST_MESSAGE';
export const REMOVE_CHAT_FROM_LIST = 'REMOVE_CHAT_FROM_LIST';

export const GET_CHAT_FEED_REQUEST = 'GET_CHAT_FEED_REQUEST';
export const GET_CHAT_FEED_FAIL = 'GET_CHAT_FEED_FAIL';
export const GET_CHAT_FEED_SUCCESS = 'GET_CHAT_FEED_SUCCESS';
export const GET_ADDITIONAL_MESSAGES_REQUEST =
  'GET_ADDITIONAL_MESSAGES_REQUEST';
export const GET_ADDITIONAL_MESSAGES_FAIL = 'GET_ADDITIONAL_MESSAGES_FAIL';
export const GET_ADDITIONAL_MESSAGES_SUCCESS =
  'GET_ADDITIONAL_MESSAGES_SUCCESS';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const PARTNER_TYPING = 'PARTNER_TYPING';
export const ADD_NEW_GROUP_MEMBER = 'ADD_NEW_GROUP_MEMBER';
export const MESSAGE_UNSENT = 'MESSAGE_UNSENT';
