export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const GET_NOTIFICATIONS_RESET = 'GET_NOTIFICATIONS_RESET';

export const READ_NOTIFICATIONS = 'READ_NOTIFICATIONS';

export const HIDE_NOTIFICATION_POPUP = 'HIDE_NOTIFICATION_POPUP';
