export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const GET_NOTIFICATIONS_RESET = 'GET_NOTIFICATIONS_RESET';
export const GET_ADDITIONAL_NOTIFICATIONS_REQUEST =
  'GET_ADDITIONAL_NOTIFICATIONS_REQUEST';
export const GET_ADDITIONAL_NOTIFICATIONS_SUCCESS =
  'GET_ADDITIONAL_NOTIFICATIONS_SUCCESS';
export const GET_ADDITIONAL_NOTIFICATIONS_FAIL =
  'GET_ADDITIONAL_NOTIFICATIONS_FAIL';
export const READ_NOTIFICATIONS = 'READ_NOTIFICATIONS';
export const HIDE_NOTIFICATION_POPUP = 'HIDE_NOTIFICATION_POPUP';

export const GET_CHAT_NOTIFICATIONS_REQUEST = 'GET_CHAT_NOTIFICATIONS_REQUEST';
export const GET_CHAT_NOTIFICATIONS_SUCCESS = 'GET_CHAT_NOTIFICATIONS_SUCCESS';
export const GET_CHAT_NOTIFICATIONS_FAIL = 'GET_CHAT_NOTIFICATIONS_FAIL';
export const ADD_CHAT_NOTIFICATION = 'ADD_CHAT_NOTIFICATION';
export const READ_CHAT_NOTIFICATION = 'READ_CHAT_NOTIFICATION';
