export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAIL = 'POSTS_GET_FAIL';
export const POSTS_ADD_LOADED = 'POSTS_ADD_LOADED';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL';
export const POST_LIKE_RESET = 'POST_LIKE_RESET';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const POST_COMMENT_RESET = 'POST_COMMENT_RESET';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';
export const POST_DELETE_RESET = 'POST_DELETE_RESET';

export const POSTS_EXPLORE_REQUEST = 'POSTS_EXPLORE_REQUEST';
export const POSTS_EXPLORE_SUCCESS = 'POSTS_EXPLORE_SUCCESS';
export const POSTS_EXPLORE_FAIL = 'POSTS_EXPLORE_FAIL';

export const SHARE_POST_REQUEST = 'SHARE_POST_REQUEST';
export const CHANGE_POST_RECEIVERS = 'CHANGE_POST_RECEIVERS';
export const RESET_POST_RECEIVERS = 'RESET_POST_RECEIVERS';
