export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAIL = 'POSTS_GET_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_GET_USER_DETAILS_REQUEST = 'POST_GET_USER_DETAILS_REQUEST';
export const POST_GET_USER_DETAILS_SUCCESS = 'POST_GET_USER_DETAILS_SUCCESS';
export const POST_GET_USER_DETAILS_FAIL = 'POST_GET_USER_DETAILS_FAIL';
