// Differences between singlePostConstans and postConstants = singlePost is relevant
// to solely one post(useReducer reducer of each post) while post is relevant to all posts(redux)

export const SINGLE_POST_LOADING = 'SINGLE_POST_LOADING';
export const SINGLE_POST_ERROR = 'SINGLE_POST_ERROR';
export const SINGLE_POST_GET_SUCCESS = 'SINGLE_POST_GET_SUCCESS';
export const SINGLE_POST_AUTHOR_DETAILS_SUCCESS =
  'SINGLE_POST_AUTHOR_DETAILS_SUCCESS';
export const SINGLE_POST_LIKE_SUCCESS = 'SINGLE_POST_LIKE_SUCCESS';
export const SINGLE_POST_BOOKMARK_SUCCESS = 'SINGLE_POST_BOOKMARK_SUCCESS';
export const SINGLE_POST_COMMENT_SUCCESS = 'SINGLE_POST_COMMENT_SUCCESS';
export const SINGLE_POST_COMMENT_LIKE_SUCCESS =
  'SINGLE_POST_COMMENT_LIKE_SUCCESS';
export const SINGLE_POST_LOADING_ADDITIONAL = 'SINGLE_POST_LOADING_ADDITIONAL';
export const SINGLE_POST_GET_ADDITIONAL_COMMENTS_SUCCESS =
  'SINGLE_POST_GET_ADDITIONAL_COMMENTS_SUCCESS';
export const SINGLE_POST_IS_REPLYING = 'SINGLE_POST_IS_REPLYING';
export const SINGLE_POST_COMMENT_REPLY_SUCCESS =
  'SINGLE_POST_COMMENT_REPLY_SUCCESS';
export const SINGLE_POST_ADD_REPLIES_SUCCESS =
  'SINGLE_POST_ADD_REPLIES_SUCCESS';
export const SINGLE_POST_REPLY_LIKE_SUCCESS = 'SINGLE_POST_REPLY_LIKE_SUCCESS';
export const SINGLE_POST_DELETE_COMMENT_SUCCESS =
  'SINGLE_POST_DELETE_COMMENT_SUCCESS';
export const SINGLE_POST_DELETE_REPLY_SUCCESS =
  'SINGLE_POST_DELETE_REPLY_SUCCESS';
