export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_PROFILE_GET_REQUEST =
  'USER_DETAILS_PROFILE_GET_REQUEST';
export const USER_DETAILS_PROFILE_GET_SUCCESS =
  'USER_DETAILS_PROFILE_GET_SUCCESS';
export const USER_DETAILS_PROFILE_GET_FAIL = 'USER_DETAILS_PROFILE_GET_FAIL';
export const USER_DETAILS_PROFILE_RELATED_REQUEST =
  'USER_DETAILS_PROFILE_RELATED_REQUEST';
export const USER_DETAILS_PROFILE_RELATED_SUCCESS =
  'USER_DETAILS_PROFILE_RELATED_SUCCESS';
export const USER_DETAILS_PROFILE_RELATED_FAIL =
  'USER_DETAILS_PROFILE_RELATED_FAIL';

export const USER_DETAILS_GET_REQUEST = 'USER_DETAILS_GET_REQUEST';
export const USER_DETAILS_GET_SUCCESS = 'USER_DETAILS_GET_SUCCESS';
export const USER_DETAILS_GET_FAIL = 'USER_DETAILS_GET_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

export const USER_SUGGESTIONS_REQUEST = 'USER_SUGGESTIONS_REQUEST';
export const USER_SUGGESTIONS_SUCCESS = 'USER_SUGGESTIONS_SUCCESS';
export const USER_SUGGESTIONS_FAIL = 'USER_SUGGESTIONS_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_STATS_REQUEST = 'USER_STATS_REQUEST';
export const USER_STATS_SUCCESS = 'USER_STATS_SUCCESS';
export const USER_STATS_FAIL = 'USER_STATS_FAIL';
export const USER_STATS_BOOKMARKS = 'USER_STATS_BOOKMARKS';
export const USER_STATS_FOLLOWING = 'USER_STATS_FOLLOWING';
